'use client';

import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, Search, Info } from 'lucide-react';

export default function FaqsPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      category: 'Open Access Energy',
      q: 'What is Open Access power procurement?',
      a: 'Open Access is a regulatory mechanism in India that allows bulk electricity consumers (with a connected load of 1 MW and above) to purchase cheaper power directly from independent power producers on the grid instead of relying solely on state-owned distribution companies (DISCOMs).'
    },
    {
      category: 'Open Access Energy',
      q: 'Who is eligible for Open Access power in India?',
      a: 'Any commercial or industrial (C&I) consumer with a contract demand of 1 MW (or 100 kW under Green Energy Open Access Rules in some states) and above connected to the grid is eligible to procure energy through Open Access.'
    },
    {
      category: 'Group Captive',
      q: 'What is the Group Captive model?',
      a: 'Under the Group Captive structure, a developer sets up a renewable energy project. The industrial consumers (off-takers) collectively hold at least 26% of equity in the project and consume at least 51% of the generated power. This model exempts consumers from paying Cross-Subsidy Surcharges (CSS).'
    },
    {
      category: 'Group Captive',
      q: 'What is the 26/51 rule under Group Captive guidelines?',
      a: 'The Electricity Rules, 2005 state that captive users must own at least 26% of the equity share capital (with voting rights) of the power generating company. They must also consume not less than 51% of the aggregate electricity generated by such plant on an annual basis.'
    },
    {
      category: 'Industrial Solar',
      q: 'What is Industrial Rooftop Solar?',
      a: 'Industrial rooftop solar involves installing solar PV panels on the roofs of factories, warehouses, and offices to generate electricity on-site. This can either run in sync with the grid (net metering) or operate as a standalone captive system.'
    },
    {
      category: 'Wind Energy',
      q: 'How does industrial wind power sourcing work?',
      a: 'Industrial wind power is sourced via grid wheeling. A wind developer constructs a project in high-wind regions (such as Gujarat, Tamil Nadu, or Rajasthan) and wheels the power through state/national transmission networks directly to your manufacturing site.'
    },
    {
      category: 'Hybrid Energy',
      q: 'What is Wind-Solar Hybrid energy?',
      a: 'Wind-Solar Hybrid setups combine solar panels and wind turbines in a single generation hub. Since solar generates during the day and wind typically peaks during the evening, hybrid systems provide a higher Capacity Utilization Factor (CUF) and a flatter, more reliable supply curve.'
    },
    {
      category: 'CAPEX',
      q: 'What is the CAPEX model in solar installations?',
      a: 'In the Capital Expenditure (CAPEX) model, the industrial consumer pays the entire upfront cost of the solar plant equipment and installation. The consumer owns the asset from day one, assumes operation & maintenance (O&M) responsibilities, and enjoys 100% of the tariff savings.'
    },
    {
      category: 'OPEX',
      q: 'What is the OPEX / RESCO model?',
      a: 'Under the Operating Expenditure (OPEX) or RESCO model, a third-party developer designs, finances, builds, and operates the solar project on the consumer\'s premises. The consumer pays no upfront capital and simply purchases the generated power at a low, pre-determined per-unit tariff.'
    },
    {
      category: 'PPA Agreements',
      q: 'What is a Power Purchase Agreement (PPA)?',
      a: 'A PPA is a long-term legally binding contract between an energy producer (generator) and a buyer (off-taker). It structures the terms of energy delivery, pricing schedules, lock-in periods, regulatory liabilities, and termination compensation over a typical 10 to 25-year tenure.'
    },
    {
      category: 'PPA Agreements',
      q: 'What is the lock-in period and tariff escalation in a PPA?',
      a: 'PPAs typically have a lock-in period of 10 to 15 years, during which neither party can terminate without significant exit penalties. Tariff escalation is a predefined annual percentage increase (usually 1-3%) built into the tariff structure, though flat-rate PPAs are also common.'
    },
    {
      category: 'Renewable Procurement',
      q: 'What is Green Tariff power procurement?',
      a: 'Green Tariff is a voluntary scheme offered by several state DISCOMs. Consumers who do not want to set up open access or onsite solar can opt to pay a slight premium tariff directly to the state utility to guarantee their power is sourced from renewable generators.'
    },
    {
      category: 'Regulatory Approvals',
      q: 'What major regulatory approvals are required for Open Access?',
      a: 'Procuring open access power requires multiple clearances: Standing Clearance or NOC from State Load Despatch Centres (SLDC), grid connectivity approvals from Transmission Companies (TRANSCOs), feeder synchronization permissions, and metering scheme approvals.'
    },
    {
      category: 'Grid Connectivity',
      q: 'What is feeder synchronization in grid connectivity?',
      a: 'Feeder synchronization is the technical matching of voltage, frequency, and phase angle parameters of the renewable plant generator with the grid network. It ensures grid stability when feeding power into state lines.'
    },
    {
      category: 'Grid Connectivity',
      q: 'What is ISTS charges waiver for renewable energy?',
      a: 'The Ministry of Power offers waivers on Inter-State Transmission System (ISTS) charges and losses for solar and wind projects commissioned within specific deadlines, making inter-state power wheeling highly economical for large industrial off-takers.'
    },
    {
      category: 'Energy Optimization',
      q: 'What is load profiling and why is it important?',
      a: 'Load profiling is the continuous mapping of your plant\'s power consumption over 15-minute intervals. Analyzing this curve allows consultants to size the renewable PPA accurately, minimizing excess generation losses and optimizing peak-shaving benefits.'
    },
    {
      category: 'Energy Optimization',
      q: 'How does Demand Side Management (DSM) reduce energy costs?',
      a: 'DSM involves scheduling high-load industrial processes (like casting, smelting, or chemical reactors) during solar peak hours. Aligning plant operations with cheap renewable generation hours yields significant spot tariff savings.'
    },
    {
      category: 'Regulatory Approvals',
      q: 'What is Cross-Subsidy Surcharge (CSS)?',
      a: 'CSS is a fee levied by state utilities on open access consumers to compensate the utility for the loss of high-paying industrial consumers, who cross-subsidize low-income and agricultural users. Group Captive structures bypass this surcharge.'
    },
    {
      category: 'Regulatory Approvals',
      q: 'What is Additional Surcharge (AS) in utility billing?',
      a: 'Additional Surcharge is levied by DISCOMs to recover the cost of stranded distribution assets and contracts resulting from open access consumers shifting their load. Captive users are exempt from AS in several states.'
    },
    {
      category: 'Energy Optimization',
      q: 'What is Net Metering vs Gross Metering?',
      a: 'Net metering records the net energy difference between what your rooftop solar exports to the grid and what you consume from the grid. Gross metering bills all generated solar power separately at a fixed feed-in tariff, while you pay normal retail rates for grid consumption.'
    },
    {
      category: 'Renewable Procurement',
      q: 'How long does the onboarding process take for Open Access?',
      a: 'A standard grid open-access setup takes 45 to 90 days. This includes load analysis, generator matchmaking, state utility approvals, metering installation, and final wheeling synchronization.'
    }
  ];

  const filteredFaqs = faqs.filter(f => 
    f.q.toLowerCase().includes(searchTerm.toLowerCase()) || 
    f.a.toLowerCase().includes(searchTerm.toLowerCase()) ||
    f.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="bg-light min-h-screen text-dark font-sans py-24">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        
        {/* Header */}
        <div className="text-center space-y-4">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary font-bold text-[10px] tracking-widest uppercase">
            <HelpCircle className="w-3.5 h-3.5" /> Knowledge Base
          </span>
          <h1 className="text-4xl md:text-6xl font-black font-heading text-dark uppercase tracking-tight leading-tight">
            FAQs & Guide
          </h1>
          <p className="text-slate-500 text-sm md:text-base max-w-2xl mx-auto font-sans">
            Detailed information on regulatory surcharges, captive guidelines, hybrid setups, and power wheeling parameters in India.
          </p>
        </div>

        {/* Search */}
        <div className="relative max-w-md mx-auto">
          <span className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
            <Search className="w-4 h-4" />
          </span>
          <input 
            type="text" 
            placeholder="Search FAQs (e.g. Group Captive, PPA)..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-white border border-slate-200 rounded-2xl pl-10 pr-4 py-3 text-xs focus:outline-none focus:border-primary transition-colors shadow-sm"
          />
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-4">
          {filteredFaqs.length > 0 ? (
            filteredFaqs.map((f, idx) => {
              const isOpen = openIndex === idx;
              return (
                <div 
                  key={idx} 
                  className="bg-white border border-slate-200 rounded-2xl overflow-hidden transition-all shadow-sm hover:shadow-md"
                >
                  <button
                    onClick={() => toggleFaq(idx)}
                    className="w-full text-left px-6 py-4 flex items-center justify-between gap-4 font-heading font-black text-dark text-xs sm:text-sm uppercase tracking-tight hover:bg-slate-50 transition-colors"
                  >
                    <span className="flex items-center gap-2.5">
                      <span className="text-[9px] font-sans font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded shrink-0">
                        {f.category}
                      </span>
                      <span>{f.q}</span>
                    </span>
                    {isOpen ? <ChevronUp className="w-4 h-4 text-slate-500 shrink-0" /> : <ChevronDown className="w-4 h-4 text-slate-500 shrink-0" />}
                  </button>
                  
                  {isOpen && (
                    <div className="px-6 pb-5 pt-1 text-slate-500 text-xs font-sans leading-relaxed border-t border-slate-100 bg-slate-50/50">
                      {f.a}
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center text-slate-400 text-xs font-sans flex flex-col items-center gap-2">
              <Info className="w-6 h-6 text-slate-300" />
              <span>No FAQs match your search criteria. Try typing &quot;PPA&quot; or &quot;CAPEX&quot;.</span>
            </div>
          )}
        </div>

        {/* Structured Data for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'FAQPage',
              'mainEntity': faqs.map(f => ({
                '@type': 'Question',
                'name': f.q,
                'acceptedAnswer': {
                  '@type': 'Answer',
                  'text': f.a
                }
              }))
            })
          }}
        />

      </div>
    </div>
  );
}
